# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.boot_timeout = 1200
  config.vm.network "forwarded_port", guest: 3000, host: 8080
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  
  # run custom shell on provision
  config.vm.provision "shell", privileged: false, inline: <<-SHELL    
    eval `ssh-agent -s`
    ssh-add ~/.ssh/vagrant-keys/vagrant
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
    sudo apt-get install -y libsqlite3-dev libbz2-dev liblzma-dev lzma
    sudo apt-get install -y python3-virtualenv 

    mkdir python3.6
    cd python3.6/
    wget https://www.python.org/ftp/python/3.6.12/Python-3.6.12.tgz
    tar -xf Python-3.6.12.tgz
    cd Python-3.6.12/
    ./configure --enable-optimizations
    sudo make install
    cd

    virtualenv candig-server-env -p ~/python3.6/Python-3.6.12/python
    source candig-server-env/bin/activate
    pip install wheel
    pip install --upgrade setuptools
    pip install candig-server

    pip install candig-ingest==1.3.1
    mkdir candig-example-data
    wget https://raw.githubusercontent.com/CanDIG/candig-ingest/master/candig/ingest/mock_data/clinical_metadata_tier1.json
    wget https://raw.githubusercontent.com/CanDIG/candig-ingest/master/candig/ingest/mock_data/clinical_metadata_tier2.json
    ingest candig-example-data/registry.db mock1 clinical_metadata_tier1.json
   
  SHELL
end
